@startuml
title: Components
footer: Open Catalogi | Components
header: Open Catalogi | Components


cloud "Azure"{
 [ADFS]  as identity
}

cloud "Internet"{
actor "User" as user
actor "Admin" as adminUser
actor "Externe Catalogus" as externalCatalouge

}

cloud "Externe Applicaties"{
package "Bronnen" {
 [Zaaksysteem]  as ZGW
 [Etc.]  as ETC
}
}

cloud "Kubernetes"{

package "Layer 5 (interaction)" {
package "React NL Design" {
 [Search UI]  as ui
}

package "Vue NL Design" {
 [Admin Interface]  as admin
}
}


package "Layer 4 (Logic)" as layer4 {
 [Synchronysations]  as service
}


package "Layer 2 (API)" as layer2 {


package "Open Catalogi App" {
 [Search API] as SearchAPI
 [Admin API] as ObjectsAPI
}


}

}

package "Layer 1 (data)" {

package "Search index" {
 [Elastic Search]  as search
}

package "Object Store" {
 [ORC]  as db
}
}

externalCatalouge <..> SearchAPI: Zoeken en Directory synchronysatie via API (PKIO)
user <..> ui : Zoeken via browser (ANONIEM)
adminUser <..> admin : Beheren via browser (JWT Claim)

ui <..> SearchAPI: Search + Directory
admin <..> ObjectsAPI: Publicaties + Catalogi + Metadata
ZGW <..> service: Synchroizatie
ETC <..> service: Synchroizatie

ObjectsAPI  .down.> db: Persist
SearchAPI  .down.> search: Look up
layer2 .down.> identity: AUTH
service .down.> ObjectsAPI: In synchronyseren van publicaties
@enduml