@startuml
title: Open Catalogi
footer: Open Catalogi | Components
header: Matrix


 [Admin Interface] as adminUI
 [User Interface] as userUi
 [CRUD API] as objectsAPI
 [Search API] as searchAPI


database "Search index" as elastic
database "Objecten opslag" as ORC

adminUI .down.> objectsAPI: Opslaan
userUi <.down. searchAPI: Opzoeken
objectsAPI .down.> ORC: Opslaan
searchAPI <.down. elastic: Zoeken
ORC .left.> elastic: Updaten


@enduml