@startuml
title: Components
footer: Open Catalogi | Components
header: Open Catalogi | Components

cloud "Identity & Access"{
 [ADFS] as identity
}

cloud "Gebruikers"{
actor "Burger" as burger
actor "Medewerker" as medewerker
actor "Admin" as adminUser
}

cloud "Externe Applicaties"{
package "Bronnen" {
 [Zaaksysteem] as ZGW
 [Etc.] as ETC
}
package "Catalogi" {
 [Externe Catalogus] as externalCatalogue
}
}

cloud "Kubernetes"{

package "Layer 5 (Interaction)" {
package "React NL Design" {
 [Search UI] as ui
}

package "Vue NL Design" {
 [Admin UI] as admin
}
}

package "Layer 4 (Logic)" as layer4 {
 [Synchronisaties] as service
}

package "Layer 2 (API)" as layer2 {

package "Open Index" {
 [Search API] as SearchAPI
}
package "Open Registers" {
 [Admin API] as ObjectsAPI
}
}

package "Layer 1 (Data)" {

package "Search Index" {
 [Elastic Search] as search
}

package "Object Store" {
 [ORC] as db
}
}

externalCatalogue <..> SearchAPI: Search + Directory
burger <..> ui: Zoeken via browser (ANONIEM)
medewerker <..> ui: Zoeken via browser (ANONIEM)
adminUser <..> admin: Beheren via browser (JWT Claim)

ui <..> SearchAPI: Search + Directory
admin <..> ObjectsAPI: Publicaties + Catalogi + Metadata
ZGW <..> service: Synchronisatie
ETC <..> service: Synchronisatie

db .left.> search: Update
ObjectsAPI .down.> db: Persist
SearchAPI <.down. search: Lookup
layer2 .down.> identity: AUTH
service .down.> ObjectsAPI: In synchroniseren van publicaties
@enduml