name: Architectuur Vraag/Voorstel
description: Stel een vraag of doe een voorstel over de standaard
title: "[architectuur]: Als een [gebruikersrol] wil ik [functionaliteit], zodat [waardetoevoeging]"
labels: [architecture]
assignees:
  - rubenvdlinde
  - RonaldvCortenberghe
body:
  - type: markdown
    attributes:
      value: |
        Voordat je een nieuwe vraag stelt of een voorstel indient, controleer dan eerst onze backlog om duplicaties te voorkomen. We structureren onze user stories in een [agile formaat](https://www.agilealliance.org/glossary/user-story-template/) 
        
        - Vermeld de *Wie* in de titel. Bijvoorbeeld, `Als een gebruiker wil ik ...`
        - Verwerk de *Wat* ook in de titel. Bijvoorbeeld, `... een duidelijke standaard`
        - Definieer de *Waarom* in de eerste alinea van de user story
        ---

        We waarderen de tijd die je neemt om een vraag te stellen of een voorstel te doen. Om de verwerking te versnellen, hebben we bepaalde details nodig.

  - type: textarea
    id: why
    attributes:
      placeholder: "Dus ...."
      label: Wat is het doel van je vraag of voorstel? Waarom is het noodzakelijk?
      description: Geef een duidelijke en nauwkeurige beschrijving van het probleem of de verbetering die je wilt adresseren.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      placeholder:|
        1. ...
        2. ...
        3. ...       
      label: De acceptatiecriteria voor het voorstel
      description: Beschrijf de voorwaarden waaraan moet worden voldaan om je vraag beantwoord of voorstel succesvol geïmplementeerd te beschouwen.
    validations:
      required: true
  - type: dropdown
    id: component-location
    attributes:
      label: Implementatiegebied
      description: Waar moet deze wijziging plaatsvinden?
      options:
        - Architectuurdocumentatie
        - Standaardenoverzicht
        - Iets anders (specificeer dit in de beschrijving)
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Aanvullende context
      description: Voeg alle andere relevante details of screenshots met betrekking tot je vraag of voorstel toe.
