name: Bug report
description: File a bug report
title: "[Bug]: "
labels: [bug]
assignees:
  - rubenvdlinde
  - RonaldvCortenberghe
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: os
    attributes:
      label: Operating system
      description: "Which operating system do you use? Please provide the version as well."
      placeholder: "macOS Big Sur 11.5.2"
    validations:
      required: true
  - type: dropdown
    id: component-location
    attributes:
      label: Project Location
      description: Where did you find the bug?
      options:
        - Frontend
        - Backend
        - Somewhere else (please specify in the description!)
    validations:
      required: true
  - type: dropdown
    id: installation
    attributes:
      label: Instalation Location
      description: Where is the project located?
      options:
        - Local
        - Remote
        - Somewhere else (please specify in the description!)
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. No need for backticks here.
      render: shell