name: Bugrapport
description: Meld een bug
title: "[Bug]: "
labels: [bug]
assignees:
  - rubenvdlinde
  - RonaldvCortenberghe
body:
  - type: markdown
    attributes:
      value: |
        Voordat je een bugrapport opent, zoek dan eerst naar het gedrag in de bestaande issues.
        
        ---
        
        Bedankt dat je de tijd neemt om een bugrapport in te dienen. Om deze bug zo snel mogelijk op te lossen, hebben we wat informatie nodig.
  - type: input
    id: os
    attributes:
      label: Besturingssysteem
      description: "Welk besturingssysteem gebruik je? Geef ook de versie op."
      placeholder: "macOS Big Sur 11.5.2"
    validations:
      required: true
  - type: dropdown
    id: component-location
    attributes:
      label: Projectlocatie
      description: Waar heb je de bug gevonden?
      options:
        - Frontend
        - Backend
        - Iets anders (specificeer dit in de beschrijving!)
    validations:
      required: true
  - type: dropdown
    id: installation
    attributes:
      label: Installatielocatie
      description: Waar is het project geïnstalleerd?
      options:
        - Lokaal
        - Extern
        - Iets anders (specificeer dit in de beschrijving!)
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bugbeschrijving
      description: Wat gebeurde er?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Stappen om te reproduceren
      description: Welke stappen moeten we nemen om deze fout te reproduceren?
  - type: textarea
    id: logs
    attributes:
      label: Relevante log-output
      description: Indien van toepassing, geef relevante log-output. Geen backticks nodig hier.
      render: shell
