name: Feature request
description: Request a feature
title: "[feature]: "
labels: [feature-request]
assignees:
  - rubenvdlinde
  - RonaldvCortenberghe
body:
  - type: markdown
    attributes:
      value: |
        Before crreating a feature request, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a feature request. To procces this request as fast as possible, we need some information.

  - type: dropdown
    id: component-location
    attributes:
      label: Project Location
      description: Where did you find the bug?
      options:
        - Frontend
        - Backend
        - Somewhere else (please specify in the description!)
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: a clear and concise description of what the problem is. E.g.,  I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.