name: Feature request
description: Request a feature
title: "[feature]: As a user I want ....."
labels: [feature-request]
assignees:
  - rubenvdlinde
  - RonaldvCortenberghe
body:
  - type: markdown
    attributes:
      value: |
        Before proposing a new feature, please ensure to double-check our backlog to avoid duplications. We structure our user stories in an[agile format](https://www.agilealliance.org/glossary/user-story-template/) 
        
        - Include the *Who* in the title. For instance, `As a user, I want …`
        - Incorporate the *What* into the title as well. For example, `… a robust site map`
        - Define the *Why* in the first paragraph of the user story
        ---

        We appreciate the time you've taken to suggest a new feature. To expedite the processing of this request, we need certain details.

  - type: textarea
    id: why
    attributes:
      placeholder: "So ...."
      label: What is the purpose of your request? Why is it necessary?
      description: Provide a clear and precise description of the issue you're aiming to address.. 
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      placeholder: |
        1. ...
        2. ...
        3. ...       
      label: The acceptance criteria for the proposed feature
      description: Detail the conditions that, if met, would mean your request has been successfully implemented.
    validations:
      required: true
  - type: dropdown
    id: component-location
    attributes:
      label: Implementation Area
      description: Where should this change occur?
      options:
        - Startpagina(Homepage)
        - Componenten overzicht (zoekpagina)
        - Componenten detailpagina
        - Organisatie detailpagina
        - Documentatiepagina's
        - Beheerschermen
        - API
        - Somewhere else (please specify in the description!)
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description:  Include any other pertinent details or screenshots related to the feature request.