name: Functionele vraag
description: Een vraag over bestaande of nieuwe functionaliteit van een OpenCatalogi component
title: "[architectuur]: Als een [gebruikersrol] wil ik [functionaliteit], zodat [waardetoevoeging]"
labels: [feature-request]
assignees:
  - rubenvdlinde
  - RonaldvCortenberghe
body:
  - type: markdown
    attributes:
      value: |
        Voordat je een nieuwe functie voorstelt, controleer dan onze backlog om duplicaties te voorkomen. We structureren onze user stories in een [agile formaat](https://www.agilealliance.org/glossary/user-story-template/) 
        
        - Vermeld de *Wie* in de titel. Bijvoorbeeld, `Als een gebruiker wil ik ...`
        - Verwerk de *Wat* ook in de titel. Bijvoorbeeld, `... een robuuste site map`
        - Definieer de *Waarom* in de eerste alinea van de user story
        ---

        We waarderen de tijd die je neemt om een nieuwe functie voor te stellen. Om de verwerking van dit verzoek te versnellen, hebben we bepaalde details nodig.

  - type: textarea
    id: why
    attributes:
      placeholder: "Dus ...."
      label: Wat is het doel van je verzoek? Waarom is het noodzakelijk?
      description: Geef een duidelijke en nauwkeurige beschrijving van het probleem dat je wilt aanpakken.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      placeholder:|
        1. ...
        2. ...
        3. ...       
      label: De acceptatiecriteria voor de voorgestelde functie
      description: Beschrijf de voorwaarden waaraan moet worden voldaan om je verzoek als succesvol geïmplementeerd te beschouwen.
    validations:
      required: true
  - type: dropdown
    id: component-location
    attributes:
      label: Implementatiegebied
      description: Waar moet deze wijziging plaatsvinden?
      options:
        - Startpagina
        - Componenten overzicht (zoekpagina)
        - Componentendetailpagina
        - Organisatiedetailpagina
        - Documentatiepagina's
        - Beheerschermen
        - API
        - Iets anders (geef dit aan in de beschrijving)
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Aanvullende context
      description: Voeg alle andere relevante details of screenshots met betrekking tot het functieverzoek toe.
