name: PublicOrganisation Check and Update

on:
  push:
    branches:
      - never

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check Organization Name
        run: |
          if [[ "${{ github.repository }}" != *".github"* ]]; then
            echo "This workflow can only be run within .github organizations."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'





      - name: Post Repository URL to OpenCatalogi API
        run: |
          curl -X POST "https://api.opencatalogi.nl/api/github_events" \
          -H "Content-Type: application/json" \
          -d '{
            "repository": {
              "html_url": "'${{ github.event.repository.html_url }}'"
            }
          }'
